### ISSUE TITLE
CVE-2022-30123 : rack (2.2.3)

### ISSUE THREAD

**Issue by meten-natuurlijk** [simplecov-ruby/simplecov-html#120]
Based on the Gemfile.lock I believe that simplecov-html makes use of rack version 2.2.3
That Rack version is has vulnerability CVE-2022-30123 (crafted requests that can cause shell escape sequences).
The solution is to rebuild using rack >= 2.2.3.1 

This also fixes CVE-2022-30122.

**Comment by meten-natuurlijk** [comment]
I think a new release needs to be built in order to make this fix visible on rubygems.org ?

**Comment by ryy** [comment]
@amatsuda 
Could you please check when you have time? my team needs to fix this issue before we can use it.
(I mentioned you, because you merged most recently.)

**Comment by william-kurosawa** [comment]
Can anyone take a look on this issue? It should be just a bump on rack version.
I guess Dependabot's PR supersedes the previous PR by @nishidayuya: https://github.com/simplecov-ruby/simplecov-html/pull/124

**Comment by nishidayuya** [comment]
#121 is older than #124, because when #121 was born, rack-2.2.6.4 (#124) was not exist in the world.

So, I'll close #121.

**Comment by amatsuda** [comment]
Ok, Ok, I just merged the dependabot PR (#124) since I even got a mention on the other issue, but please note that the "vulnerability" on rack gem here does not at all affect your applications' security.

Gems bundled here via `Gemfile.lock` in this repo is nothing but development dependencies that are used only for clones of this Git repo. Not your applications that depend on simplecov-html. Please check `Gemfile.lock` in your apps and confirm what I said.
Also, simplecov-html is a static site generator. This product is not a kind of software that runs a web server and processes web requests on your machine. Hence, even if you run simplecov with such "vulnerable" version of Rack, there's no way the attackers can attack your production server.

Again, I just merged the PR in order to calm you guys down, and also to show you that the project is not dead, but please learn that you generally need not to care about the content of `Gemfile.lock` in someone else's repo.

**Comment by william-kurosawa** [comment]
Thank you Matsuda-san! I totally agree and understand, sorry to bother the simplecov team for that. 

My applications itself have requirements to use latest version of rack. What happens to my company (and possibly for some others) is that there are vulnerabilities checkers (AWS Inspector) that scan containers images, looks into package managers files and eventually find the rack version in the "Gemfile.lock". 

I will look further on AWS Inspector if is possible to suppress this type of finding without suppressing real dependencies  vulnerabilities.

**Comment by amatsuda** [comment]
@william-kurosawa Oh, thank you for the explanation! Now I understand the triggers and people's motivation for issues like this. Sounds fair enough actually!

**Comment by william-kurosawa** [comment]
@blombard , just to inform you, I am also waiting for another release, but that might be out of Matsuda's hands as it needs to be published to Rubygems. 
What I am doing at the moment is fetching directly from the specific commit on github with
```ruby
  gem 'simplecov-html', git: 'https://github.com/simplecov-ruby/simplecov-html',
                        ref: 'ea52c023962c449156d9348a827666c981bd3831'
```

I am also trying to reach a AWS Inspector specialist to understand if they don't have a way around this alerts for code that is not even in the image, it's just a lock file inside a dependency with mention to another dependency..

**Comment by blombard** [comment]
@william-kurosawa Perfect, exactly what I needed for now 👌

**Comment by jordanbreen28** [comment]
@amatsuda is it possible to get a release of this change?
